### PR TITLE
Fix for the Django 1.7+

### PR DESCRIPTION
**Pull request by antonvino**
Django now relies on Python having json and does not have simplejson in utils anymore

### CODE REVIEW

**Comment by fredrikand** [comment]
This change would be much appriciated. Whats keeping it from being merged?

**Comment by PiotrCzapla** [comment]
Hi,
Is this project still active, the pull request is super simple I wonder why noone just hit merge button.

**Comment by lcafaro** [comment]
Confirmed working with Django 1.8.3 on Python 2.7.6. I had to patch manually, why is no one merging?
Thanks.

**Comment by grantmcconnaughey** [comment]
Hello. Django-chartit is not compatible with Django 1.7+. I released a fork called [django-chartit2](https://github.com/grantmcconnaughey/django-chartit2). It is now on [PyPI](https://pypi.python.org/pypi/django_chartit2/).

**Comment by atodorov** [comment]
Hello everyone,
I've just taken first steps to revive this project by cleaning up and merging with the django-chartit2 fork by @grantmcconnaughey. 

Since this issue has been fixed in 63d2d4a0 I'm closing this PR. If you'd like to remove the simplejson dependency and instead use the json module please open another PR.

**Pull request closed without merging**
